[package]
name = "http-protocol-spec"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol-spec = {path = "../lib"}
paste = "1.0.15"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
derive_builder = "0.20.2"
concat-idents = "1.1.5"
chrono = "0.4.42"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.43.0", features = ["io-util", "macros", "rt", "net", "rt-multi-thread"] }
async-trait = "0.1.88"


[[bin]]
name = "client"
path = "src/client.rs"


